wurst/_handles/Group.wurst
wurst/event/OnUnitEnterLeave.wurst

An update due to bugs discussed in #13 (both should be solved by this).

fixed OnUnitEnterLeave

---

wurst/data/HashList.wurst

I also think we should add .isEmpty() to all data structures, what do you think?

fix broken wording and add .isEmpty and .contains methods

---

wurst/math/Maths.wurst

I think more math functionalities should be added too, but will have to think about it.

add euler's constant to the Maths package

---

wurst/_handles/Group.wurst

it was a cool idea
it was a beautiful dream
but in the end, it did not work out
rip the relationship between group and grouputils </3

fix group requiring grouputils insanity

---

wurst/dummy/InstantDummyCaster.wurst

It is useful with any kind of projectiles.
I'm in doubt if it is ever needed, but think it's not for me to decide.

Remake of InstantDummyCaster with vec3 position argument

---

wurst/_handles/Effect.wurst
wurst/_handles/Item.wurst
wurst/_handles/Player.wurst
wurst/_handles/Unit.wurst

Includes wrappers for unit, item and effect native methods.
Changelog for each commit lists particular methods that have been accounted for.

Addition of patch 1.29 handle-related natives.

---

wurst/data/Table.wurst

Adds possibility to save/load hashtables in Table

Add Save/Load functions for hashtables in data/Table

---

wurst/data/Table.wurst

Following missing methods have been added:
- hasHandle
- removeString
Reorganized Table.wurst code to improve readability.

Table: Add hasHandle and removeString methods.

---

wurst/_handles/primitives/Boolean.wurst
wurst/_handles/primitives/PrimitivesTests.wurst

Made shorter boolean functions and added tests for it

Update Boolean.wurst and PrimitivesTests.wurst

---

wurst/_handles/Trigger.wurst

Fixed existing functions to return values as original ones do & added missing ones

Fixed trigger API

---

wurst/math/Quaternion.wurst

https://github.com/wurstscript/WurstStdlib2/pull/112#issuecomment-421681012

Quaternion warnings

---

wurst/math/Raycast.wurst

Contains
For 2D:
For 3D:
Of course, there are lots of extra things that can be implemented but they can be surplus in Wc3 for stdlib.

Raycast.wurst

---

wurst/_handles/Item.wurst
wurst/_handles/Unit.wurst

Not sure for stdlib, but this is a quite common task for me.

InventoryIterator

---

wurst/closures/ClosureEvents.wurst
wurst/event/EventHelper.wurst

Mouse events update

---

wurst/_handles/Image.wurst

Layer is too generic, it should be left available.

Layer -> ImageLayer

---

wurst/_handles/Widget.wurst

Forgot to do this in the previous commit. My mistake.

Make widget.isAliveTrick public

---

wurst/objediting/AbilityObjEditing.wurst

https://github.com/wurstscript/WurstStdlib2/issues/207

windwalkdef fix  #207

---

wurst/data/buffer/BufferInterface.wurst
wurst/network/GamecacheBuffer.wurst
wurst/objediting/ObjEditingCommons.wurst
wurst/objediting/UnitObjEditing.wurst
wurst/objediting/UpgradeObjEditing.wurst
wurst/objediting/presets/ChannelAbilityPreset.wurst
wurst/util/Printing.wurst

Fixing warnings introduced after recent Wurst engine updates.

Warnings fix

---

wurst/event/DamageEvent.wurst

Removed useless lines in removeListener().

Removed useless lines.

---

wurst/objediting/BuffObjEditing.wurst

for https://github.com/wurstscript/WurstStdlib2/issues/187

added support for custompath for bufficons

---

wurst/util/TimerUtils.wurst

Fixing a bug introduced by the last commit.

Fix for TimedLoop module

---

wurst/_wurst/Reflection.wurst

Added new pseudo-natives for debugging memory leaks.
see https://github.com/wurstscript/WurstScript/commit/4adc23008880d2f6305d9f7207722ae3ed97aa04

New reflection natives

---

wurst/closures/ClosureForGroups.wurst

Following #218 discussion, added a new forUnitsInRange with collision filtering.

forUnitsInRange with collision filtering

---

wurst/_handles/Ability.wurst
wurst/_handles/Group.wurst
wurst/_handles/Item.wurst
wurst/_handles/Unit.wurst
wurst/_handles/_Handles.wurst

First small batch of implemented functions from 1.31 PTR

Added new PTR functions for Group, Unit, Ability, Item

---

wurst/_handles/Unit.wurst

Fixed a division by zero in the Unit package when a unit had zero max mana.

Fixed a division by zero case.

---

wurst/_handles/Framehandle.wurst
wurst/_handles/Trigger.wurst
wurst/_handles/_Handles.wurst

New framehandle natives wrapper class

Adding FrameHandle wrapperclass

---

wurst/data/LinkedList.wurst
wurst/data/LinkedListTests.wurst
wurst/objediting/ObjectIds.wurst
wurst/util/StringUtils.wurst
wurst/util/StringUtilsTests.wurst

Moved some functions from StringUtils to LinkedList and removed StingUtil import from ObjectIds to avoid cyclic dependency

Added new string extension functions

---

wurst/_handles/Framehandle.wurst
wurst/closures/ClosureFrames.wurst

* Improved the framhandle package (better consistency in the API, better documentation, vec2 support and screen constants and some other minor stuff)
* Added closure support for framehandle
What type of documentation you would want in the ClosureFrames package?

More framehandle support

---

wurst/_handles/Multiboard.wurst
wurst/closures/ClosureEvents.wurst

- multiboars in lua do not accept null values, so added a workaround
- lua checks member access, fixed a related NPE in ClosureTimers

fixed some errors encountered while testing with Lua

---

wurst/util/TimerUtils.wurst

Added the possibility to have different periods between different module implementations by overriding the new getPeriod() function.

Update TimedLoop module

---

wurst/_handles/Item.wurst
wurst/_wurst/TypeCasting.wurst
wurst/data/Table.wurst

Added new handles to Table/TypeCast
Minor fix in Item
Moved function of saveUbersplat to be adjacent to loadUbersplat

Added new handles to Table/TypeCast

---

wurst/_handles/Destructable.wurst

Added new functions to control gates
Reworked native functions for controlling elevators

Added new tuple gate, elevator

---

wurst/_handles/Unit.wurst

The bug causes the map to freeze.

Fix inifinite recursion in unit.isAllyOf

---

wurst/data/LinkedList.wurst
wurst/data/LinkedListTests.wurst

Allows to transfer elements from a list in a constant time.

Add splice method for linked list

---

wurst/util/SoundUtils.wurst

overload ondestroy as not all sound instances are recycled

---

wurst/util/Colors.wurst

Color code found here https://www.hiveworkshop.com/threads/need-help-with-player-color-codes-and-where-to-find-them-all.314460/.
A 1 was missing. color(164, 11, 51) instead of color(164, 111, 51).

Fixing peanut color code

---

wurst/util/Knockback3.wurst

Enables Knockback3 to be used in environments where GetLocationZ can desync

add configurable heightmap provider

---

wurst/_handles/Ability.wurst

Wrapers for Blz[Set/Get]Ability[Tooltip/ExtenedTooltip/Icon/e.t.c.]

Wrapers for ability natives / Spaces to tabs

---

wurst/_handles/Unit.wurst

Missed unit function

---

wurst/_handles/primitives/String.wurst

There are such functions for uppercase, no idea why there was no lowercase counterparts.

Add string.isLower() & string.firstLower()

---

wurst/file/ChunkedString.wurst
wurst/file/FileIO.wurst
wurst/file/SaveLoadData.wurst
wurst/network/SyncSimple.wurst

Encapsulation, memory leaks and useless actions fixed.

Prettify ChunkedString and FileIO

---

wurst/_handles/Unit.wurst

addAbility(id, level)
addPermanentAbility(id)
addPermanentAbility(id, level)

More unit extension functions

---

wurst/_handles/Framehandle.wurst

Removing useless import?

---

wurst/_handles/Framehandle.wurst
wurst/event/EventHelper.wurst

Added new wrappers for Item trigger functions and new Framehandle funcs

---

wurst/util/StandardTextTags.wurst

It would be nice for these to output the text tag in case further modification is desired, e.g. filtering visibility.

Changed texttag shortcuts to output the tag.

---

wurst/_handles/primitives/Boolean.wurst
wurst/_handles/primitives/Integer.wurst
wurst/_handles/primitives/PrimitivesTests.wurst

XOR doesn't have an operator and I figure this is the next best thing.

Added some boolean operations.

---

wurst/_wurst/assets/Assets.wurst

Should have been added in #374 #375, I forgot about it.

Added buffIds & itemIds to Assets.wurst

---

wurst.build
wurst/dummy/DummyRecycler.wurst
wurst/objediting/ObjectIds.wurst

introduce commaList(LinkedList<int>) and commaList(LinkedList<string>)

---

wurst/_handles/Framehandle.wurst

- added real whole screen coord for frames
- added settext and settext per players basis
- added world ui frame

updated framehandles

---

wurst/_handles/Framehandle.wurst

Framehandles settings null player

---

wurst/_handles/Unit.wurst
wurst/event/EventHelper.wurst

`EventData`
```
/** Returns `true` if the damage done is done with Unit's attack. */
static function isAttackDamage() returns bool
return BlzGetEventIsAttack()
```
`Unit`
````
public function unit.startAbilityCooldown(int abilCode)
BlzStartUnitAbilityCooldown(this, abilCode, this.getAbilityCooldown(abilCode, this.getAbilityLevel(abilCode) - 1))
public function unit.startAbilityCooldown(int abilCode, real cooldown)
BlzStartUnitAbilityCooldown(this, abilCode, cooldown)
```

Missing natives and some hot docs

---

wurst/util/Cinematic.wurst

Example usage: https://bitbucket.org/Cokemonkey11/kill-katydma/src/043f1d3aca0cf492823cc1456d2fd89989289466/wurst/Cinematic.wurst#lines-111

Add cinematic framework

---

wurst/_wurst/assets/AbilityIds.wurst

Missing bigBadVoodoo abilityId 'AOvd'

Add bigBadVoodoo abilityId

---

wurst/_handles/primitives/String.wurst
wurst/_handles/primitives/StringTests.wurst
wurst/data/LinkedList.wurst

Closes https://github.com/wurstscript/WurstStdlib2/issues/427
Added a lexicographic string comparison function to `String.wurst` and integrated into `LinkedList` for out-of-the-box sorting of `LinkedList<string>`.

Add string comparison function

---

wurst/_handles/Unit.wurst

Wrapping up some native functions related to item stock.

Added unit method for item stock handling

---

wurst/closures/ClosureEvents.wurst

https://github.com/wurstscript/WurstStdlib2/issues/433

add warning when trying to add event listners to a unit without an index

---

wurst/_wurst/assets/AbilityIds.wurst
wurst/_wurst/assets/Orders.wurst
wurst/_wurst/assets/Soundsets.wurst
wurst/objediting/AbilityObjEditing.wurst

Added a few missing assets.
Why does the soundSets.wurst file contains comments like `// RazorMane` without the sound set string?

Added a few missing assets.
