wurstscript/WurstStdlib2

- util/Printing.wurst
- util/UnitIndexer.wurst
Basically this offers a proper way to address index and deindex events with a deterministic order - 
everything put into onIndex will happen AFTER an unit is indexed
everything put into onDeindex will happen BEFORE an unit is deindexed
also made it possible to call unit.deindex() which deindexes the unit and returns whether an unit was initially indexed to begin with, this is useful in cases where you want control over indexing (like when you use unit recycling systems)
also added overloads for the print function.
> [UnitIndexer] added handlers for onIndex and onDeindex 

- wurst/event/DamageDetection.wurst
- wurst/event/OnUnitEnterLeave.wurst
Apparently, ever since the order of compiletime calls has become deterministic, the compiletime(x) function is just messing things up. I had to remove this in order to get the same order in compiletime/game.
> remove compiletime call in OnUnitEnterLeave

- wurst/objediting/AbilityObjEditing.wurst
- wurst/objediting/BuffObjEditing.wurst
- wurst/objediting/DestructableObjEditing.wurst
- wurst/objediting/ItemObjEditing.wurst
- wurst/objediting/UnitObjEditing.wurst
- wurst/objediting/UpgradeObjEditing.wurst
This is code that I've been using for a while but always put off adding it to the stdlib. My idea is to make data directly set by the constructor retrievable afterwards, this makes it easier to create object data frameworks since it allows you to pass newly constructed definitions as parameters, and then have your system decide what to do with the ids (and where and how to store them).
> add the ability to retrieve set ids from definitions

- wurst/_handles/Group.wurst
- wurst/util/GroupUtils.wurst
Also, .destr() now calls .release()
The code is tested in game, and it works with my systems (that use a bunch of groups) without leaking. I can't guarantee more than that. This is impossible to test because get handle id is unavailable during compiletime. This also breaks GroupTests.wurst because it now uses getGroup() during group iteration.
> add GroupUtils and change Group.wurst to use its functionalities

- wurst/_handles/Quest.wurst
- wurst/_handles/QuestItem.wurst
> Quest and Questitem extensions

- wurst/_handles/Unit.wurst
- wurst/_handles/Widget.wurst
- wurst/_handles/primitives/Integer.wurst
- wurst/_handles/primitives/Real.wurst
Added in a few extension functions I feel are useful to have, Most of which has a direct Native equivalent that it's making use of.
> Added few extension functions (Unit, Widget, Int, Real)

- wurst/_handles/primitives/Boolean.wurst
- wurst/_wurst/ErrorHandling.wurst
- wurst/closures/Execute.wurst
- wurst/data/BufferAdapters.wurst
- wurst/file/LocalFiles.wurst
- wurst/file/MultifileIO.wurst
- wurst/file/Persistable.wurst
- wurst/file/PreloadIO.wurst
- wurst/network/Network.wurst
- wurst/network/SyncSimple.wurst
Changelog:
* Added ability to suppress error messages with the global `suppressErrorMessages` variable. This is used in the `Execute` package, in function `try` to facilitate a very basic form of exception-handling. Rationale: `Persistable` relies on the `deserialize` function to throw an error when a deserialization fails (tampered data, missing file, etc.), but since this is acceptable behaviour, and the error is properly handled upstream with `try`, there is no need for the player to see the inevitable error message. This shouldn't affect regular errors.
* Renamed `MultiIO` to `MultifileIO`, renamed `SimpleIO` to `PreloadIO`. Rationale: `PreloadIO` is meant to be a simple wrapper around the Preload API, and does no checks for Local Files. The reasoning is that there may be use cases …
> Improvements to FileIO and Network packages

- wurst/data/LinkedList.wurst
- wurst/data/LinkedListTests.wurst
Current `addAt` function is wrong because it creates the new `LLEntry`, that is connected with the `dummy`. I fixed it. Now the new `LLEntry` is correctly connected with the old `LLEntry` in the place of which it is inserted.
I mean `entry.next` and `entry.prev` relations
> Fix addAt function in LinkedList class

- wurst/objediting/TargetsAllowed.wurst
- wurst/objediting/UnitObjEditing.wurst
Would also be really helpful if we could comment each value so it would be clearer what the differences is between `allies` and `friends` for example.
Any feedback on the choice of suffixing the values with `_t` to avoid the namespace collision?
> Add TargetsAllowed to prevent typos

- wurst/_handles/Item.wurst
- wurst/_handles/Unit.wurst
Reorganized Item.wurst package:
- Getters before setters, if applicable. This is true also for natives
introduced in patch 1.29
- Natives added in patch 1.29 still remain on the botton, to match
common.j organization.
- Removed unnecessary white spaces
Unit.wurst package:
- Added itemCount extension method for returning unit's current item
count
- Added isInventoryFull extension method for checking if unit inventory
is full
- Added itemSlot extension method for retrieving slot number for
provided item
- Renamed addItem extension method to addItemById
Following natives have been accounted for:
native          GetItemPlayer   takes item whichItem returns player
native          SetItemDropOnDeath  takes item whichItem, boolean flag returns nothing
native          SetItemDroppable takes item …
> Item and Unit package improvements.

- wurst/objediting/BuffObjEditing.wurst
- wurst/util/Preloader.wurst
Replaces int2fourchar() with .toRawCode, as int2fourchar() is now deprecated.
> Replace deprecated functions

- wurst/_handles/Unit.wurst
Just added a simple function, unit.removeItemById. Functionality pretty much copied from unit.hasItemById(int itemId). Useful when a user wants to remove an item and doesn't care how many of it there are or where it sits.
> Update Unit.wurst to include "remove item by ID"

- wurst/_handles/Item.wurst
- wurst/_handles/Unit.wurst
Following extension methods have been defined:
- public function unit.dropItemPoint(item itm, real x, real y) returns boolean
- public function unit.dropItemSlot(item itm, int slot) returns boolean
- public function unit.dropItemTarget(item itm, widget target) returns boolean
- public function unit.useItem(item itm) returns boolean
- public function unit.useItemPoint(item itm, real x, real y) returns boolean
- public function unit.useItemTarget(item itm, widget target) returns boolean
- public function item.isAlive() returns boolean
- public function item.isPickupable() returns boolean
> Addition of missing and utility unit & item natives.

- wurst/_handles/Unit.wurst
- wurst/dummy/Fx.wurst
- wurst/util/Knockback3.wurst
Added missing getCurrentValue functions for functions that already had getDefaultValue: PropWindow, TurnSpeed, AcquireRange
Added functions with angle as parameter/return value for prop window functions.
Fixed a problem with getDefaultPropWindow:
The native returns the value in degrees, so it has to be converted to radians first. Usually all natives use radians.
Typo: AcquireRange
> Add missing extension functions + prop window fix

- wurst/_handles/Player.wurst
Added function to enable / disable user control for the local player (similar to what ``SetUserControlForce`` does in blizzard.j)
> Added EnableUserControl()

- wurst/_handles/TimerDialog.wurst
- wurst/math/Angle.wurst
Wrappers for Timer Dialog API from common.j and small fixes in Angle package
> new TimerDialog package

- wurst/_wurst/TypeCasting.wurst
- wurst/data/Table.wurst
These functions allow to use triggeraction & triggercondition in generics. It can be useful, e.g. if you manage triggers dynamically and want to remove actions and conditions to avoid leaks
> Functions to work with triggeraction & triggercondition

- wurst/file/PreloadIO.wurst
Contrary to my tests, WC3 can't read more than 223 characters from a player name, which broke the file IO. Reverting this to it's original value.
> Revert raising limit on preloader

- wurst/closures/ClosureTimers.wurst
This allows for flexibility to use ClosurerTimers while keeping
a reference to the timer itself. This is especially important when
dealing with `timerdialog`.
> Add ClosureTimers functions as extension methods of `timer`

- wurst/dummy/DummyCaster.wurst
Allow access to the unit associated with the DummyCaster instance.
For example I need this to bind a damage listener that detects when the casted spell actually hits the target.
> Allow access to unit associated with DummyCaster instance

- wurst/_wurst/TypeCasting.wurst
- wurst/data/LinkedListTests.wurst
See #190 
StringHash is not unique, so use linear probing to resolve colliding hashes.
> Add linear probing to stringToIndex

- wurst/_handles/Unit.wurst
- wurst/_handles/Widget.wurst
The trick applies to widgets in general and not just units.
Note that there is a technical difference in the implementation:
`unit.isAliveTrick` used the `GetUnitState` native whereas `widget.isAliveTrick`
uses the `GetWidgetLife` native. I'm unaware if there are any differences
in the output of said native functions. I assume not.
> Move unit.isAliveTrick to widget.isAliveTrick

- wurst/_handles/Unit.wurst
The previous behaviour was to only accept unit targets.
This change is backward-compatible.
The underlying native
native UnitDamageTarget             takes unit whichUnit, widget target, real amount, boolean attack, boolean ranged, attacktype attackType, damagetype damageType, weapontype weaponType returns boolean
accepts `widget` targets so I can't think of a reason that the wrapper function `unit.damageTarget` shouldn't do so as well.
This pull request is an updated version of https://github.com/wurstscript/WurstStdlib2/pull/192 without the unrelated `isAliveTrick` changes.
> Generalize unit.damageTarget to target widgets

- wurst/Wurst.wurst
- wurst/_handles/Image.wurst
- wurst/_handles/Item.wurst
- wurst/_handles/Player.wurst
- wurst/_handles/Unit.wurst
- wurst/_wurst/Annotations.wurst
- wurst/_wurst/Basics.wurst
- wurst/_wurst/ErrorHandling.wurst
- wurst/_wurst/TypeCasting.wurst
- wurst/_wurst/Wurstunit.wurst
- wurst/data/LinkedList.wurst
- wurst/dummy/DummyRecycler.wurst
- wurst/event/OnUnitEnterLeave.wurst
- wurst/math/Interpolation.wurst
- wurst/math/Vectors.wurst
- wurst/objediting/AbilityObjEditing.wurst
- wurst/objediting/ObjEditingNatives.wurst
- wurst/objediting/ObjectIds.wurst
- wurst/objediting/UnitObjEditing.wurst
- wurst/util/Colors.wurst
- wurst/util/GroupUtils.wurst
- wurst/util/MapBounds.wurst
- wurst/util/Preloader.wurst
- wurst/util/Printing.wurst
- wurst/util/StringUtils.wurst
Since Wurst will now gives a warning for undefined annotations, this PR adds the predefined annotations to the standard library in `Annotations.wurst`.
> Define standard annotations

- wurst/closures/ClosureForGroups.wurst
Changed the new forUnitsInRange() to allow for the () -> syntax.
I believe the callback has to be the last argument.
> ClosureForGroups fix

- wurst/closures/ClosureEvents.wurst
- wurst/event/DamageEvent.wurst
- wurst/event/EventHelper.wurst
DamageEvent now supports new 1.31 natives:
- Unreduced listeners (damage event that fires before the damage is reduced by any damage reducing effect such as armor)
- attacktype, damagetype and weapontype handling
- Better and easier native spell detection (It is now detected by checking if the attacktype is ATTACK_TYPE_NORMAL)
Some things to consider:
- A way to deprecated EventListener.add(EVENT_UNIT_DAMAGED) is needed since we have a general event now
- If you set damage to zero or less during the unreduced phase, the reduced events will not fire (that's how it works natively).
> Damage Event for 1.31

- wurst/event/DamageEvent.wurst
Since 0 damage are now passed, this needed to be removed.
> DamageEvent Hotfix

- wurst/_handles/Framehandle.wurst
Improved the documentation a bit.
Important line: "Always get the framehandle outside of the local scope"
I will add to this PR as I find more useful notes.
> Improving the framehandle documentation.

- wurst/data/HashList.wurst
Small addition. Should be backwards compatible.
I need this to implement an efficient `staticItr()` in a module.
> Add reset method to HLIterator

- wurst/_wurst/Reflection.wurst
Otherwise, they cannot be used by others.
> Make reflection natives public

- wurst/math/Vectors.wurst
This issue has been there since 2014 according to the [WurstScript changelog](https://github.com/wurstscript/WurstScript/blob/4adc23008880d2f6305d9f7207722ae3ed97aa04/CHANGELOG.md#1400-2014-03-15).
> Rename vec2.op_div to vec2.op_divReal

- wurst/dummy/DummyRecycler.wurst
This change allows to use dummy casters with "attackonce" order. It may be useful in the following pattern:
`new DummyCaster().castTarget(AbilityIds.poisonSting, 1, OrderIds.attackonce, target)`
The target unit will be poisoned.
This does not break compatibility since the dummy won't attack unless explicitly ordered thanks to the special ability based on permanent invisibility.
> Allow dummy caster unit to attack when ordered

- wurst/_handles/Effect.wurst
- wurst/math/Matrices.wurst
- wurst/math/MatricesTests.wurst
- wurst/math/Quaternion.wurst
- wurst/math/QuaternionTests.wurst
Related to #297 
1.29 patch brought the effect-orientation control to the game. It used Euler-angles in order `X-Y-Z` which was quite confusing according to names `Yaw-Pitch-Roll`. In the latest patches this was changed. Now, `Yaw` defines rotation around `Z` axis and `Roll` defines rotation around `X` axis and the rotation order (according to `Yaw-Pitch-Roll`) has become `Z-Y-X`.
This PR fixes the issues in the standard library which appeared with the game's changes. Thanks to Blizzard for non-mentioning these changes in the patch notes so it took me a while to notice the problem.
```
Tests succeeded: 22/22
>> All tests have passed successfully!
Tests succeeded: 35/35
>> All tests have passed successfully!
```
> mat3 and quat fixes for effect orientation

- wurst/_wurst/MagicFunctions.wurst
- wurst/objediting/BuffObjEditing.wurst
Would allow to create objects at compiletime with comfort without needing to declare a `compiletime` function with an argument of the needed type each time. What's more, that is the only way to allow to create both an object of type `class A` and an object of type `class B extends A` at compiletime: if you declare `compiletime` functions with arguments of the concrete types, you would not be able to create an object of type B without casting it from A to B, and if you declare generic `compiletime` function, it would be ambiguous with the built-in ones.
> make `compiletime` magic function generic

- wurst/_handles/Framehandle.wurst
Wrappers for `BlzEnableCursor` and `BlzSetMousePos`
`setMousePos(vec2)` and `framehandle.setMousePos()` that use a trick to manipulate the mouse cursor in `framehandle` coordinate system
> Mouse functions for Framhandle package

- wurst/network/SyncSimple.wurst
Async bools/ints/reals can come from custom frames, this introduces handy wrappers of string.sync for these.
> Add .sync method for primitives

- wurst/util/Knockback3.wurst
- Add `forget` to the API to remove a unit from Knockback3 control
- Move some cleanup behavior into an ondestroy
- Slightly simplify elasticity check
> three changes to Knockback3

- wurst/objediting/ItemObjEditing.wurst
Reforged added a field to the item object definition allowing us to set the number of stack for an item
> Added setter for the maxStack item field

- wurst/file/SaveLoadData.wurst
Even an empty ChunkedString has one (empty) chunk, so you should check it's length instead of checking whether it has a chunk.
> Fix reading empty files

- wurst/file/ByteBuffer.wurst
I'm sorry for the bug I've missed when submitted the ByteBuffer. :S Here is the fix. Without it, reading from it in a while loop with hasByte() condition works wrong: you could miss some bytes.
> [HOTFIX] Reading from a ByteBuffer with a while loop

- wurst/objediting/BuffObjEditing.wurst
In fact, buffs' parameters do not depend on levels. You cannot specify levels of a buff and it only uses it's level 1's parameters, so it's stupid to have to specify the level every time. This PR provides additional convenience overloads.
> Don't require lvl in buffs editing

- wurst/_wurst/assets/Soundsets.wurst
Look like blizzard changed the string used to reference Troll batrider soundset.
> Updated Trollbatrider soundset

- wurst/data/LinkedList.wurst
This variable isn't needed. It's always `true` until after the if-condition is evaluated in the final step of the for-loop.
> Removed superfluous variable in LinkedList.joinBy.

- wurst/objediting/presets/HeroPreset.wurst
If you are using HeroPreset.wurst, you can't use stuff like TargetsAllowed or ArmorType and etc. which are publicly imported in UnitObjEditing.wurst. You have to import UnitObjEditing.wurst again or import TargetsAllowed.wurst and ObjEditingCommons.wurst separately.
This fix solves the problem.
> UnitObjEditing public import in HeroPreset

- wurst/data/LinkedList.wurst
This problem can cause compilation failure, keep the same as the master branch.
https://github.com/wurstscript/WurstStdlib2/blob/master/wurst/data/LinkedList.wurst#L127
> [pre1.29] fix LinkedList.removeAt

- wurst/util/Knockback3.wurst
Closes #385
The underlying issue here is that SetUnitFlyHeight always obeys unit min flyheight.
Note that Get/Set min fly height is not working with new blizzard natives, so there's no safe way to knockback3 flying units.
Another reasonable solution here would be to automatically provide a 2D knockback for flying units
> [knockback3] knockback3 ignore air units by default

- wurst/util/Knockback3.wurst
Closes #383
See https://github.com/Cokemonkey11/knockback3-demo/ for demo map
Knockback3 behaves poorly when a unit ends up on a cliff edge (gets stuck).
This PR improves the behavior in a few ways:
- A unit is no longer considered to have hit a wall in the following cases:
* The unit is ascending and the next tick puts the unit at higher Z than the terrain
* The units current position before next tick is not walkable
- When a unit strikes a wall, instead of losing all horizontal velocity, the unit bounces, knocking in the opposite direction. Friction applies as in the bouncing off the ground case.
It is still possible to get stuck on cliffs (!) but this PR makes it significantly easier to get un-stuck.
> fix knockback3 getting stuck on cliffs

- wurst/file/SaveLoadData.wurst
Because of that you can't load file with just passing file name like "myFileName".
Wurst SaveLoadData package docs and website examples were using it without extension too, so it was confusing at first why it wasn't working.
> Fixed loadData not checking for extension

- wurst/dummy/DummyRecycler.wurst
The queue of DelayNodes is not setup correctly. This results in a wrong order of DelayNodes and next references being null for intermediate nodes.
DelayNode makes use of timers, so unit tests are not possible. For showing correctness and showing the errors of the previous implementation I made a modified version with a unit test here: https://bin.wurstlang.org/jajiwenuwe.wurst
This makes it easy to see the issues of the old implementation without the need to run a map.
The unit test first uses the new implementation and afterwards the old one. The old implementation will result in a nullpointer exception and wrongly sorted queue.
> fix DelayNode

- wurst/file/SaveLoadData.wurst
- wurst/objediting/presets/ChannelAbilityPreset.wurst
If you use channel ability preset package, then you will most likely want to set an icon, since you don't wanna use std one.
This change will remove need in redundant Icons.wurst imports in every ability package, which use ChannelAbilityPreset.
> Public import for Icons.wurst in ChannelAbilityPreset

- wurst/_handles/Unit.wurst
I didn't know it was possible to retrieve a unit icon, then I saw [this hive workshop comment](https://www.hiveworkshop.com/threads/still-no-natives-to-get-unit-type-icons-etc.337444/#post-3516994), I thought adding this method would be useful, at least to know that it's possible.
> Added getUnitIcon method

- wurst/_handles/QuestItemTests.wurst
- wurst/_handles/QuestTests.wurst
Add tests for the quest and quest item handles, leveraging the mocks added in https://github.com/wurstscript/WurstScript/pull/1060. Prefers testing through the Wurstscript handle implementations over the natives if possible.
Tried to base these on existing tests and the style guide, feedback is of course welcome!
> Add tests for mocked Quest and Quest Item handles.

- wurst/_handles/Unit.wurst
Used to remove hero glow on a unit.
I wonder what exactly is considered a glow though.
> Added unit showTeamGlow native

- wurst/_wurst/assets/Soundsets.wurst
On 1.36, "Hellscream" doesn't seem to exist.
I didn't look for the reason as to why, but I remember some odd change about Hellscream name for reforged, maybe it's related?
https://us.forums.blizzard.com/en/warcraft3/t/why-do-we-hate-grom-now/14474
> Fixed Grom Hellscream soundset path

- wurst/objediting/UnitObjEditing.wurst
The "upor" or "Art - Portrait Model File" field was added in the patch 2.0, it's a field used to set the portrait model, I believe its purpose is related to the new skin feature.
From what I am seeing, it's set to default for most standard editor units, if you make a new custom unit and change its model, you're going to have to change this portrait field too.
> Added setPortraitModelFile method

- wurst/dummy/DummyCaster.wurst
Following conversation in the discord, support vec3 origins. Keep support for vec2 origins and convert them internally.
> Add support to DummyCaster package for vec3 origins
